### ISSUE TITLE
Taxonomy field Tags editor fails after upgrade to 3.0.1

### ISSUE THREAD

**Issue by OlivianVarareanu** [OrchardCMS/OrchardCore#19919]
### Describe the bug

After upgrading an existing Orchard Core application 2.2.1 to 3.0.1, opening the admin edit page of a content item that has a Taxonomy field using the **Tags** editor fails with a Razor compilation error:

<img width="1913" height="907" alt="Image" src="https://github.com/user-attachments/assets/7435d9e3-9722-46b5-b5cf-6d7c6563a0c6" />

```
/Areas/OrchardCore.Taxonomies/Views/TaxonomyField-Tags.Edit.cshtml(65,33): Error RZ1030: TagHelper attributes must be well-formed.
```

I did not override this view anywhere in my project.

Workaround: changing the **Editor** of the taxonomy field from *Tags* to *Default* in the content type definition makes the edit page load again.

### Orchard Core version

3.0.1, all `OrchardCore.*` packages from nuget.org, all on 3.0.1:

- OrchardCore.Application.Cms.Targets, OrchardCore.Application.Cms.Core.Targets, OrchardCore.Module.Targets, OrchardCore.Theme.Targets
- OrchardCore.Taxonomies, OrchardCore.Contents, OrchardCore.ContentFields, OrchardCore.ContentManagement, OrchardCore.DisplayManagement, OrchardCore.ResourceManagement and others

Environment:

- .NET 10 (`net10.0`)
- `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` 10.0.8
- IDE: JetBrains Rider
- Upgraded from Orchard Core [2.2.1]

### To Reproduce

1. Upgrade an Orchard Core application to 3.0.1 (eg: from [2.2.1]).
2. Have a content type with a Taxonomy field whose **Editor** is set to *Tags*.
3. Go to the admin and open the edit page of a content item of that type.
4. See the error `RZ1030: TagHelper attributes must be well-formed` and the exception page.

### Expected behavior

The edit page loads and renders the Tags editor for the taxonomy field, as it did before the upgrade.

### Logs and screenshots

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.CompilationFailedException: One or more compilation failures occurred:
      /Areas/OrchardCore.Taxonomies/Views/TaxonomyField-Tags.Edit.cshtml(65,33): Error RZ1030: TagHelper attributes must be well-formed.
         at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.CompileAndEmit(String relativePath)
         at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.OnCacheMiss(String normalizedPath)
      --- End of stack trace from previous location ---

         ...
```

**Comment by AniketDeshmane** [comment]
Hey there! Just letting you know that I've raised a PR to fix this issue: #19921.

**Comment by hishamco** [comment]
Please address https://github.com/OrchardCMS/OrchardCore/pull/19921#issuecomment-5772909622

**Comment by sebastienros** [comment]
Have you checked if you have a custom csproj file that changes how razor compilation is done?
Can you try with a fresh clone of OC on 3.0.1?
