### ISSUE TITLE
Fix ambiguous string.Join overload in OrchardCore.Features/Views/Admin/Features.cshtml for .NET 10 - 3.0.0

### ISSUE THREAD

**Issue by ShivamGovBuilt** [OrchardCMS/OrchardCore#19439]
### Describe the bug

When navigating to /Admin/Features, the page throws a Razor compilation error:

  ▎ The call is ambiguous between the following methods or properties: string.Join(string?, params
  ▎ ReadOnlySpan<object?>) and string.Join(string?, params ReadOnlySpan<string?>)

  Root Cause: Features.cshtml (line 120) in OrchardCore.Features uses a collection expression [...] passed to
  string.Join(). In .NET 10, new ReadOnlySpan overloads were added to string.Join, making the call ambiguous when the
  compiler can't infer whether the array is string[] or object[].

### Orchard Core version

3.0.0

### To Reproduce

When navigating to /Admin/Features, the page throws a Razor compilation error:

### Logs and screenshots

<img width="1908" height="964" alt="Image" src="https://github.com/user-attachments/assets/973b4cb5-1fec-4f4f-92a6-1df833a17458" />

**Comment by hishamco** [comment]
I will check this one immediately

**Comment by hishamco** [comment]
I'm unable to reproduce this in the latest bits

**Comment by gvkries** [comment]
I think this can only happen if you're using an older version of C#. Please at least update to v13. @Skrypt had this problem too, maybe he can help you fix it. It doesn't seem to be caused by OC alone.

**Comment by ShivamGovBuilt** [comment]
After updating <LangVersion> to 13.0, the issue was resolved.

Thank you, @gvkries  and @hishamco for your help!

I'm closing this issue.

**Comment by Skrypt** [comment]
Thanks, did not dreamed this one at least. 😉
