### PR TITLE
Fix RZ1030 TagHelper compilation error in Taxonomy tags editor

### LINKED ISSUE #19919: Taxonomy field Tags editor fails after upgrade to 3.0.1
### Describe the bug

After upgrading an existing Orchard Core application 2.2.1 to 3.0.1, opening the admin edit page of a content item that has a Taxonomy field using the **Tags** editor fails with a Razor compilation error:

Image

```
/Areas/OrchardCore.Taxonomies/Views/TaxonomyField-Tags.Edit.cshtml(65,33): Error RZ1030: TagHelper attributes must be well-formed.
```

I did not override this view anywhere in my project.

Workaround: changing the **Editor** of the taxonomy field from *Tags* to *Default* in the content type definition makes the edit page load again.

### Orchard Core version

3.0.1, all `OrchardCore.*` packages from nuget.org, all on 3.0.1:

- OrchardCore.Application.Cms.Targets, OrchardCore.Application.Cms.Core.Targets, OrchardCore.Module.Targets, OrchardCore.Theme.Targets
- OrchardCore.Taxonomies, OrchardCore.Contents, OrchardCore.ContentFields, OrchardCore.ContentManagement, OrchardCore.DisplayManagement, OrchardCore.ResourceManagement and others

Environment:

- .NET 10 (`net10.0`)
- `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` 10.0.8
- IDE: JetBrains Rider
- Upgraded from Orchard Core [2.2.1]

### To Reproduce

1. Upgrade an Orchard Core application to 3.0.1 (eg: from [2.2.1]).
2. Have a content type with a Taxonomy field whose **Editor** is set to *Tags*.
3. Go to the admin and open the edit page of a content item of that type.
4. See the error `RZ1030: TagHelper attributes must be well-formed` and the exception page.

### Expected behavior

The edit page loads and renders the Tags editor for the taxonomy field, as it did before the upgrade.

### Logs and screenshots

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.CompilationFailedException: One or more compilation failures occurred:
      /Areas/OrchardCore.Taxonomies/Views/TaxonomyField-Tags.Edit.cshtml(65,33): Error RZ1030: TagHelper attributes must be well-formed.
         at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.CompileAndEmit(String relativePath)
         at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.OnCacheMiss(String normalizedPath)
      --- End of stack trace from previous location ---

         ...
```

### PR DESCRIPTION
**Pull request by AniketDeshmane**
Fixes #19919.

After upgrading to 3.0.1, the Taxonomy Tags editor throws `Error RZ1030: TagHelper attributes must be well-formed.`

This is caused by nested double-quotes inside the HTML attribute:
`data-create-tag-error-message="@T["Error creating tag"]"`

This PR fixes the crash by safely wrapping the outer HTML attribute in single quotes:
`data-create-tag-error-message='@T["Error creating tag"]'`

### CODE REVIEW

**Comment by hishamco** [comment]
@gvkries seems this happened one more time :)

**Comment by gvkries** [comment]
I don't think this is the correct fix:

1. The issue was reported against version 3.0.1, but this area has been completely reworked on the main branch.
2. On the main branch, these strings are HTML-encoded, so the failure scenario addressed by this PR cannot occur.

Please reproduce the issue before attempting to fix it.

**Comment by sebastienros** [comment]
@AniketDeshmane can you prove that you actually saw the error, then it disappeared after changing these quotes? Your comment seems to imply it but it feels really unexpected that quotes are the issue here.
